### PR TITLE
Removed "ignore-root" to protect users

### PR DESCRIPTION
**Pull request by schucko1337**
"--ignore-root" parameter removed to protect users who (for some reason) don't know how to use a server properly

### CODE REVIEW

**Comment by ByteExceptionM** [comment]
Please do not push into master branch

**Review by ByteExceptionM — DISMISSED** [review]
Please do not push into master branch

**Comment by derklaro** [comment]
Just changed the base for @robertschuck to `progress`

**Comment by ByteExceptionM** [comment]
Let's talk about this before we make these changes.

**Comment by derklaro** [comment]
Will be merged soon

**Pull request merged**
