### PR TITLE
Changed Download Servers for some BungeeCord Jar Forks

### PR DESCRIPTION
**Pull request by JanDragon**

### CODE REVIEW

**Comment by derklaro** [comment]
Can you please test all other download links of spigot and bungee, too?

**Comment by JanDragon** [comment]
Yes I will do this in the evening. No problem.

**Comment by JanDragon** [comment]
Fixed now every Download Link and Formatted the Code.

**Comment by derklaro** [comment]
You cannot remove the shortspigot, please re-add the spigot

**Comment by JanDragon** [comment]
The Problem is I can't find a Download Mirror and the Old one is down. If someone have it its no Problem so I can add It back. Or I can add it with no Function.

**Comment by derklaro** [comment]
So of the old mirror is down IT is correct to remove the download but please fix the build issues depending to that commit

**Comment by JanDragon** [comment]
Yes I will do this.

**Comment by JanDragon** [comment]
Its now added back.

**Comment by derklaro** [comment]
Do not add it back remove it completly

**Pull request closed without merging**
