### PR TITLE
Added Uninstall Command for Addons

### PR DESCRIPTION
**Pull request by JanDragon**

### CODE REVIEW

**Comment by derklaro** [comment]
So the main thing I am thinking about is, that under windows the file has to be unloaded first, to prevent an `IOException`. Please check if the command fully executes correctly under windows.

**Comment by derklaro** [comment]
@JanDragon can you please give your answer?

**Review by ByteExceptionM — CHANGES_REQUESTED** [review]
The command is not executed correctly - The error that the file is in use is thrown out (On Windows)

**Comment by derklaro** [comment]
So you can try to close the ClassLoader of the Application... But i don't know if this could help

**Comment by derklaro** [comment]
So just rechecked. You can try close the https://github.com/reformcloudproject/reformcloud/blob/progress/reformcloud-library/src/main/java/systems/reformcloud/addons/loader/AddonMainClassLoader.java loader of the addon which you can access https://github.com/reformcloudproject/reformcloud/blob/b4741f22b384e06d1381cf05d03037d75e7f1f5d/reformcloud-library/src/main/java/systems/reformcloud/addons/JavaAddon.java#L89 making the call package-private (for example)

**Pull request closed without merging**
